// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.1
// source: tsdb.proto

package tsdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TsdbHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   uint32 `protobuf:"varint,1,opt,name=items,proto3" json:"items,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TsdbHeader) Reset() {
	*x = TsdbHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TsdbHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsdbHeader) ProtoMessage() {}

func (x *TsdbHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsdbHeader.ProtoReflect.Descriptor instead.
func (*TsdbHeader) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{0}
}

func (x *TsdbHeader) GetItems() uint32 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *TsdbHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TsdbMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start    uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End      uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Addr     int64  `protobuf:"varint,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Refblock int32  `protobuf:"varint,4,opt,name=refblock,proto3" json:"refblock,omitempty"`
	Refitems int32  `protobuf:"varint,5,opt,name=refitems,proto3" json:"refitems,omitempty"`
}

func (x *TsdbMeta) Reset() {
	*x = TsdbMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TsdbMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsdbMeta) ProtoMessage() {}

func (x *TsdbMeta) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsdbMeta.ProtoReflect.Descriptor instead.
func (*TsdbMeta) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{1}
}

func (x *TsdbMeta) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TsdbMeta) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *TsdbMeta) GetAddr() int64 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *TsdbMeta) GetRefblock() int32 {
	if x != nil {
		return x.Refblock
	}
	return 0
}

func (x *TsdbMeta) GetRefitems() int32 {
	if x != nil {
		return x.Refitems
	}
	return 0
}

type TsdbIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Block     int32  `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Offset    int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Len       int32  `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *TsdbIndex) Reset() {
	*x = TsdbIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TsdbIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsdbIndex) ProtoMessage() {}

func (x *TsdbIndex) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsdbIndex.ProtoReflect.Descriptor instead.
func (*TsdbIndex) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{2}
}

func (x *TsdbIndex) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TsdbIndex) GetBlock() int32 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *TsdbIndex) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TsdbIndex) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

type TsdbData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TsdbData) Reset() {
	*x = TsdbData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TsdbData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsdbData) ProtoMessage() {}

func (x *TsdbData) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsdbData.ProtoReflect.Descriptor instead.
func (*TsdbData) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{3}
}

func (x *TsdbData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TsdbData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tsdb_proto protoreflect.FileDescriptor

var file_tsdb_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x73, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x73,
	0x64, 0x62, 0x22, 0x3c, 0x0a, 0x0a, 0x54, 0x73, 0x64, 0x62, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x7e, 0x0a, 0x08, 0x54, 0x73, 0x64, 0x62, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x66, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x66, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x69, 0x0a, 0x09, 0x54, 0x73, 0x64, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x22, 0x3c, 0x0a, 0x08, 0x54,
	0x73, 0x64, 0x62, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d, 0x5a, 0x0b, 0x66, 0x61, 0x63,
	0x61, 0x64, 0x65, 0x2f, 0x74, 0x73, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tsdb_proto_rawDescOnce sync.Once
	file_tsdb_proto_rawDescData = file_tsdb_proto_rawDesc
)

func file_tsdb_proto_rawDescGZIP() []byte {
	file_tsdb_proto_rawDescOnce.Do(func() {
		file_tsdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_tsdb_proto_rawDescData)
	})
	return file_tsdb_proto_rawDescData
}

var file_tsdb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tsdb_proto_goTypes = []interface{}{
	(*TsdbHeader)(nil), // 0: tsdb.TsdbHeader
	(*TsdbMeta)(nil),   // 1: tsdb.TsdbMeta
	(*TsdbIndex)(nil),  // 2: tsdb.TsdbIndex
	(*TsdbData)(nil),   // 3: tsdb.TsdbData
}
var file_tsdb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tsdb_proto_init() }
func file_tsdb_proto_init() {
	if File_tsdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tsdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TsdbHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TsdbMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TsdbIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TsdbData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tsdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tsdb_proto_goTypes,
		DependencyIndexes: file_tsdb_proto_depIdxs,
		MessageInfos:      file_tsdb_proto_msgTypes,
	}.Build()
	File_tsdb_proto = out.File
	file_tsdb_proto_rawDesc = nil
	file_tsdb_proto_goTypes = nil
	file_tsdb_proto_depIdxs = nil
}
